# Docker Compose file for koronavilkku-backend
version: '3'
services:
  database:
    container_name: "covid19-db"
    image: "postgres:12"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: 'exposure-notification'
      POSTGRES_USER: 'devserver'
      POSTGRES_PASSWORD: 'devserver-password'
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data as volume
  exposure-notification:
    container_name: "exposure-notification"
    network_mode: "host"
    environment:
      - EN_SERVER_PORT=8080
    ports:
     - "8080:8080"
     - "9080:9080"
    build:
      context: .
      dockerfile: ./exposure-notification/Dockerfile
  publish-token:
    container_name: "publish-token"
    environment:
      - PT_SERVER_PORT=8081
      - PT_MANAGEMENT_SERVER_PORT=9081
    ports: 
      - "8081:8081"
      - "9081:9081"
    network_mode: "host"
    build:
      context: .
      dockerfile: ./publish-token/Dockerfile
volumes:
  database-data: # easier management with docker volumes