logging:
  config: src/main/resources/logback-dev.xml

server:
  port: ${PT_SERVER_PORT:8081}

management:
  server:
    port: ${PT_MANAGEMENT_SERVER_PORT:9081}

spring:
  datasource:
    url: "${PT_DATABASE_URL:jdbc:postgresql://localhost:5433/exposure-notification}"
    username: "${PT_DATABASE_USERNAME:devserver}"
    password: "${PT_DATABASE_PASSWORD:devserver-password}"
  flyway:
    clean-on-validation-error: true
